#!/usr/bin/env python


import rospy
from sensor_msgs.msg import PointCloud2
from laser_assembler.srv import *


rospy.init_node("scan_persistence_node")
pointcloud_out_publisher = rospy.Publisher("cloud_out", PointCloud2, queue_size=10)

rospy.loginfo("Waiting for service assemble_scans2")
rospy.wait_for_service("assemble_scans2")
rospy.loginfo("Service assemble_scans2 available")

r = rospy.Rate(20)

while not rospy.is_shutdown():
  
  try:
    assemble_scans2 = rospy.ServiceProxy('assemble_scans2', AssembleScans2)
    resp = assemble_scans2(rospy.Time(0, 0), rospy.get_rostime())
    pointcloud_out_publisher.publish(resp.cloud)
    rospy.loginfo("Published persistent pointcloud")
    
  except rospy.ServiceException, e:
    rospy.logwarn("Service call failed: %s"%e)
    continue

  r.sleep()

